import { db } from '@/db';
import { notificationPreferences } from '@/db/schema';

async function main() {
    const sampleNotificationPreferences = [
        // User ID 1 (Vivek Sharma): email enabled, SMS enabled, push enabled
        {
            userId: 1,
            type: 'transactional',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'transactional',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'transactional',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'reminder',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'reminder',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'reminder',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'promotional',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'promotional',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'promotional',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'system',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'system',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            type: 'system',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },

        // User ID 2 (Priya Patel): email enabled, SMS enabled, push disabled
        {
            userId: 2,
            type: 'transactional',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'transactional',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'transactional',
            channel: 'push',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'reminder',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'reminder',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'reminder',
            channel: 'push',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'promotional',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'promotional',
            channel: 'sms',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'promotional',
            channel: 'push',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'system',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'system',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 2,
            type: 'system',
            channel: 'push',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },

        // User ID 3 (Rahul Kumar): email enabled, SMS disabled, push enabled
        {
            userId: 3,
            type: 'transactional',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'transactional',
            channel: 'sms',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'transactional',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'reminder',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'reminder',
            channel: 'sms',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'reminder',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: new Date('2024-02-17T22:00:00Z').toISOString(),
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 3,
            type: 'promotional',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'promotional',
            channel: 'sms',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: 3,
            type: 'promotional',
            channel: 'push',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'system',
            channel: 'email',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'system',
            channel: 'sms',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 3,
            type: 'system',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },

        // User ID 4 (Anita Desai): email enabled, SMS enabled, push enabled
        {
            userId: 4,
            type: 'transactional',
            channel: 'email',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'transactional',
            channel: 'sms',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'transactional',
            channel: 'push',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'reminder',
            channel: 'email',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'reminder',
            channel: 'sms',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'reminder',
            channel: 'push',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'promotional',
            channel: 'email',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'promotional',
            channel: 'sms',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'promotional',
            channel: 'push',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'system',
            channel: 'email',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'system',
            channel: 'sms',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 4,
            type: 'system',
            channel: 'push',
            enabled: true,
            locale: 'hi-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },

        // User ID 5 (Arjun Singh): email disabled, SMS enabled, push enabled
        {
            userId: 5,
            type: 'transactional',
            channel: 'email',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'transactional',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'transactional',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'reminder',
            channel: 'email',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            userId: 5,
            type: 'reminder',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'reminder',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'promotional',
            channel: 'email',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            userId: 5,
            type: 'promotional',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'promotional',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'system',
            channel: 'email',
            enabled: false,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'system',
            channel: 'sms',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            type: 'system',
            channel: 'push',
            enabled: true,
            locale: 'en-IN',
            snoozeUntil: null,
            mute: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        }
    ];

    await db.insert(notificationPreferences).values(sampleNotificationPreferences);
    
    console.log('✅ Notification preferences seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});