import { db } from '@/db';
import { notifications } from '@/db/schema';

async function main() {
    const sampleNotifications = [
        {
            userId: 1,
            type: 'transactional',
            priority: 'high',
            title: 'Bus Booking Confirmed - Mumbai to Delhi',
            content: 'Your bus journey from Mumbai to Delhi on 15th March has been confirmed. Seat: 12A, Departure: 8:30 PM from Dadar Terminal.',
            channel: 'email',
            locale: 'en',
            templateKey: 'booking-confirmation',
            data: {
                bookingId: 'BUS123456',
                route: 'Mumbai to Delhi',
                seatNumber: '12A',
                departureTime: '8:30 PM',
                departureDate: '15-03-2024',
                terminal: 'Dadar Terminal',
                amount: '₹1,250',
                passengerName: 'Vivek Sharma'
            },
            status: 'delivered',
            scheduledAt: new Date('2024-02-28T10:30:00').toISOString(),
            sentAt: new Date('2024-02-28T10:30:15').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-02-28T10:25:00').toISOString(),
            updatedAt: new Date('2024-02-28T10:30:15').toISOString(),
        },
        {
            userId: 2,
            type: 'transactional',
            priority: 'high',
            title: 'Train Ticket Booked - Rajdhani Express',
            content: 'Your train ticket for Rajdhani Express from Delhi to Mumbai on 20th March is confirmed. Coach: B1, Berth: 25.',
            channel: 'sms',
            locale: 'en',
            templateKey: 'booking-confirmation',
            data: {
                pnr: 'PNR8901234567',
                trainName: 'Rajdhani Express',
                trainNumber: '12951',
                route: 'Delhi to Mumbai',
                coach: 'B1',
                berth: '25',
                departureDate: '20-03-2024',
                departureTime: '4:55 PM',
                amount: '₹3,480',
                passengerName: 'Priya Patel'
            },
            status: 'sent',
            scheduledAt: new Date('2024-03-01T14:20:00').toISOString(),
            sentAt: new Date('2024-03-01T14:21:10').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-01T14:15:00').toISOString(),
            updatedAt: new Date('2024-03-01T14:21:10').toISOString(),
        },
        {
            userId: 3,
            type: 'reminder',
            priority: 'normal',
            title: 'Journey Reminder - Chennai to Bangalore Bus',
            content: 'Your bus journey is tomorrow! Chennai to Bangalore departure at 11:00 PM from Koyambedu. Please arrive 30 minutes early.',
            channel: 'push',
            locale: 'en',
            templateKey: 'journey-reminder',
            data: {
                bookingId: 'BUS789012',
                route: 'Chennai to Bangalore',
                departureTime: '11:00 PM',
                departureDate: '10-03-2024',
                terminal: 'Koyambedu Bus Terminal',
                seatNumber: '18B',
                passengerName: 'Rahul Kumar'
            },
            status: 'delivered',
            scheduledAt: new Date('2024-03-09T09:00:00').toISOString(),
            sentAt: new Date('2024-03-09T09:00:05').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-08T18:00:00').toISOString(),
            updatedAt: new Date('2024-03-09T09:00:05').toISOString(),
        },
        {
            userId: 4,
            type: 'transactional',
            priority: 'high',
            title: 'Flight Booking Confirmed - Mumbai to Goa',
            content: 'Your flight from Mumbai to Goa on 25th March is confirmed. Flight: 6E 345, Departure: 2:15 PM from Terminal 2.',
            channel: 'email',
            locale: 'en',
            templateKey: 'booking-confirmation',
            data: {
                pnr: 'AI9876543',
                flightNumber: '6E 345',
                airline: 'IndiGo',
                route: 'Mumbai to Goa',
                departureDate: '25-03-2024',
                departureTime: '2:15 PM',
                terminal: 'Terminal 2',
                gate: 'A12',
                amount: '₹8,450',
                passengerName: 'Anita Desai'
            },
            status: 'delivered',
            scheduledAt: new Date('2024-03-02T16:45:00').toISOString(),
            sentAt: new Date('2024-03-02T16:45:20').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-02T16:40:00').toISOString(),
            updatedAt: new Date('2024-03-02T16:45:20').toISOString(),
        },
        {
            userId: 5,
            type: 'transactional',
            priority: 'high',
            title: 'Hotel Booking Confirmed - Hyderabad',
            content: 'Your stay at Grand Hyatt Hyderabad from 18th to 20th March is confirmed. Room: Deluxe King, Check-in: 3:00 PM.',
            channel: 'email',
            locale: 'en',
            templateKey: 'booking-confirmation',
            data: {
                bookingId: 'HTL567890',
                hotelName: 'Grand Hyatt Hyderabad',
                city: 'Hyderabad',
                checkInDate: '18-03-2024',
                checkOutDate: '20-03-2024',
                roomType: 'Deluxe King Room',
                numberOfNights: 2,
                amount: '₹12,500',
                guestName: 'Arjun Singh'
            },
            status: 'delivered',
            scheduledAt: new Date('2024-03-03T11:20:00').toISOString(),
            sentAt: new Date('2024-03-03T11:20:30').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-03T11:15:00').toISOString(),
            updatedAt: new Date('2024-03-03T11:20:30').toISOString(),
        },
        {
            userId: 1,
            type: 'promotional',
            priority: 'low',
            title: 'Special Offer - 20% Off on Pune to Hyderabad Route',
            content: 'Book your bus tickets from Pune to Hyderabad and save 20%! Use code TRAVEL20. Valid till 31st March.',
            channel: 'push',
            locale: 'en',
            templateKey: 'travel-offer',
            data: {
                discountPercentage: '20%',
                promoCode: 'TRAVEL20',
                route: 'Pune to Hyderabad',
                validTill: '31-03-2024',
                maxDiscount: '₹500',
                minBookingAmount: '₹1,000'
            },
            status: 'delivered',
            scheduledAt: new Date('2024-03-05T10:00:00').toISOString(),
            sentAt: new Date('2024-03-05T10:00:12').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-05T09:45:00').toISOString(),
            updatedAt: new Date('2024-03-05T10:00:12').toISOString(),
        },
        {
            userId: 3,
            type: 'reminder',
            priority: 'normal',
            title: 'Train Journey Tomorrow - Kolkata to Mumbai',
            content: 'Your train journey on Howrah Mail is tomorrow at 10:55 PM. Coach: S7, Berth: 42. Please carry valid ID.',
            channel: 'sms',
            locale: 'en',
            templateKey: 'journey-reminder',
            data: {
                pnr: 'PNR2468135790',
                trainName: 'Howrah Mail',
                trainNumber: '12809',
                route: 'Kolkata to Mumbai',
                departureDate: '22-03-2024',
                departureTime: '10:55 PM',
                coach: 'S7',
                berth: '42',
                passengerName: 'Rahul Kumar'
            },
            status: 'failed',
            scheduledAt: new Date('2024-03-21T08:00:00').toISOString(),
            error: 'SMS delivery failed - invalid mobile number',
            retryCount: 2,
            lastRetryAt: new Date('2024-03-21T09:15:00').toISOString(),
            nextRetryAt: new Date('2024-03-21T11:00:00').toISOString(),
            failoverChannel: 'email',
            failoverStatus: 'pending',
            createdAt: new Date('2024-03-20T20:00:00').toISOString(),
            updatedAt: new Date('2024-03-21T09:15:00').toISOString(),
        },
        {
            userId: 2,
            type: 'transactional',
            priority: 'high',
            title: 'Flight Booking Confirmed - Delhi to Jaipur',
            content: 'Your domestic flight from Delhi to Jaipur on 28th March is confirmed. Flight: AI 463, Departure: 7:30 AM from Terminal 3.',
            channel: 'email',
            locale: 'en',
            templateKey: 'booking-confirmation',
            data: {
                pnr: 'AI1357924680',
                flightNumber: 'AI 463',
                airline: 'Air India',
                route: 'Delhi to Jaipur',
                departureDate: '28-03-2024',
                departureTime: '7:30 AM',
                arrivalTime: '8:45 AM',
                terminal: 'Terminal 3',
                amount: '₹6,890',
                passengerName: 'Priya Patel'
            },
            status: 'queued',
            scheduledAt: new Date('2024-03-06T15:30:00').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-06T15:25:00').toISOString(),
            updatedAt: new Date('2024-03-06T15:30:00').toISOString(),
        },
        {
            userId: 4,
            type: 'system',
            priority: 'normal',
            title: 'App Update Available - New Features Added',
            content: 'A new version of TravelEasy app is available with enhanced booking features and real-time tracking. Update now!',
            channel: 'push',
            locale: 'en',
            templateKey: 'system-update',
            data: {
                appVersion: '2.4.0',
                updateType: 'feature',
                features: ['Real-time bus tracking', 'Offline ticket storage', 'Enhanced UI'],
                updateSize: '45MB',
                isOptional: false
            },
            status: 'delivered',
            scheduledAt: new Date('2024-03-07T12:00:00').toISOString(),
            sentAt: new Date('2024-03-07T12:00:08').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-07T11:45:00').toISOString(),
            updatedAt: new Date('2024-03-07T12:00:08').toISOString(),
        },
        {
            userId: 5,
            type: 'promotional',
            priority: 'low',
            title: 'Weekend Getaway - Kochi Hotel Deals',
            content: 'Plan your weekend in beautiful Kochi! Book hotels with up to 30% discount. Includes breakfast and free WiFi.',
            channel: 'email',
            locale: 'en',
            templateKey: 'travel-offer',
            data: {
                city: 'Kochi',
                discountPercentage: '30%',
                dealType: 'Weekend Special',
                inclusions: ['Breakfast', 'Free WiFi', 'Airport pickup'],
                validDates: '15-03-2024 to 31-03-2024',
                startingPrice: '₹2,999'
            },
            status: 'sent',
            scheduledAt: new Date('2024-03-08T14:00:00').toISOString(),
            sentAt: new Date('2024-03-08T14:00:25').toISOString(),
            retryCount: 0,
            failoverStatus: 'not_attempted',
            createdAt: new Date('2024-03-08T13:50:00').toISOString(),
            updatedAt: new Date('2024-03-08T14:00:25').toISOString(),
        }
    ];

    await db.insert(notifications).values(sampleNotifications);
    
    console.log('✅ Notifications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});